import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { MdAddReaction } from 'react-icons/md';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Simple Share',
  description: 'Generated by create next app',
};

const navLinks = [
  {
    href: '/posts/create',
    text: <MdAddReaction className='size-7 text-slate-500 md:size-8' />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <section className='px-2 font-mono md:mx-auto md:w-1/2'>
          <nav className='flex items-end justify-between py-4'>
            <Link
              href={'/'}
              className='text-xl font-bold uppercase md:text-3xl'
            >
              Simple Share
            </Link>
            <div className='space-x-1'>
              {navLinks.map(({ href, text }) => (
                <Link href={href} key={href}>
                  {text}
                </Link>
              ))}
            </div>
          </nav>
          <div>{children}</div>
        </section>
      </body>
    </html>
  );
}
